import csv


def export_csv(filepath, result, data, rec=None, research=None):
    with open(filepath, 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)

        writer.writerow(['DCF Valuation Report'])
        writer.writerow([])

        writer.writerow(['Valuation Summary'])
        writer.writerow(['Current Price', result.get('current_price')])
        writer.writerow(['Intrinsic Value', result.get('intrinsic_value')])
        writer.writerow(['Upside / Downside', result.get('upside')])
        writer.writerow(['Growth Rate', result.get('growth_rate')])
        writer.writerow(['WACC', result.get('wacc')])
        writer.writerow(['Terminal Value', result.get('terminal_value')])
        writer.writerow(['Enterprise Value', result.get('enterprise_value')])
        writer.writerow(['Equity Value', result.get('equity_value')])
        writer.writerow(['Projection Years', data.get('projection_years')])
        writer.writerow(['Terminal Growth Rate', data.get('terminal_growth_rate')])
        writer.writerow([])

        if rec:
            writer.writerow(['Recommendation'])
            writer.writerow(['Action', rec.get('action')])
            writer.writerow(['Confidence', rec.get('confidence')])
            writer.writerow(['Summary', rec.get('summary')])
            for r in rec.get('reasons', []):
                writer.writerow(['Reason', r])
            writer.writerow([])

        writer.writerow(['Cash Flow Projections'])
        writer.writerow(['Year', 'Historical FCF', 'Projected FCF', 'PV of Projected FCF'])

        hist = data.get('historical_fcfs', [])
        proj = result.get('projected_fcfs', [])
        wacc = result.get('wacc', 0.1)

        for dt, fcf in hist:
            writer.writerow([dt.year, fcf, '', ''])

        last_yr = hist[-1][0].year if hist else 2024
        for i, fcf in enumerate(proj, 1):
            yr = last_yr + i
            pv = fcf / (1 + wacc) ** i
            writer.writerow([yr, '', fcf, pv])

        writer.writerow([])
        writer.writerow(['Generated by DCF Stock Valuation Model'])
